const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Behaviors.Physics,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Sine: 0},
	{PlayBTN: 0},
	{MenuTittle: 0},
	{DarkBackground: 0},
	{SettingsBackground: 0},
	{CloseBTN: 0},
	{SoundBTN: 0},
	{MusicBTN: 0},
	{HomeBTN: 0},
	{RestartBTN2: 0},
	{Rotate: 0},
	{EndgameEffect: 0},
	{HighscorePanel: 0},
	{HomeBTN2: 0},
	{RestartBTN: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{Physics: 0},
	{WallLimits: 0},
	{Mouse: 0},
	{GlowEffectMerge: 0},
	{GameParticles: 0},
	{GlowEffectMerge2: 0},
	{NextCoin: 0},
	{Tween: 0},
	{Pin: 0},
	{DropCoin: 0},
	{AimLine: 0},
	{Timer: 0},
	{GameOverLimit: 0},
	{level: 0},
	{GameCoin: 0},
	{DragDrop: 0},
	{DragObject: 0},
	{GameplayBackground: 0},
	{TouchPosition: 0},
	{TouchArea: 0},
	{ScoreHUD: 0},
	{GameFloor: 0},
	{LimitTrigger: 0},
	{Fade: 0},
	{CompanyLogo: 0},
	{MenuBackground: 0},
	{LiteTween: 0},
	{MenuXrp: 0},
	{NextUI: 0},
	{GameScoreFont: 0},
	{InstructionsBTN: 0},
	{MainScoreUI: 0},
	{SettingsBTN: 0},
	{MergeEffect: 0},
	{GameOverScoreFont: 0},
	{Instructions: 0},
	{resized_shared0sheet: 0},
	{Type2: 0},
	{Type1: 0},
	{sound: 0},
	{music: 0},
	{Highscore: 0},
	{Score: 0},
	{Current: 0},
	{Next: 0},
	{Endline: 0},
	{Errorline: 0},
	{DropTime: 0}
];

self.InstanceType = {
	PlayBTN: class extends self.ISpriteInstance {},
	MenuTittle: class extends self.ISpriteInstance {},
	DarkBackground: class extends self.ISpriteInstance {},
	SettingsBackground: class extends self.ISpriteInstance {},
	CloseBTN: class extends self.ISpriteInstance {},
	SoundBTN: class extends self.ISpriteInstance {},
	MusicBTN: class extends self.ISpriteInstance {},
	HomeBTN: class extends self.ISpriteInstance {},
	RestartBTN2: class extends self.ISpriteInstance {},
	EndgameEffect: class extends self.ISpriteInstance {},
	HighscorePanel: class extends self.ISpriteInstance {},
	HomeBTN2: class extends self.ISpriteInstance {},
	RestartBTN: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	WallLimits: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	GlowEffectMerge: class extends self.IParticlesInstance {},
	GameParticles: class extends self.IParticlesInstance {},
	GlowEffectMerge2: class extends self.IParticlesInstance {},
	NextCoin: class extends self.ISpriteInstance {},
	DropCoin: class extends self.ISpriteInstance {},
	AimLine: class extends self.ISpriteInstance {},
	GameOverLimit: class extends self.ISpriteInstance {},
	GameCoin: class extends self.ISpriteInstance {},
	DragObject: class extends self.ISpriteInstance {},
	GameplayBackground: class extends self.ISpriteInstance {},
	TouchPosition: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ISpriteInstance {},
	ScoreHUD: class extends self.ISpriteFontInstance {},
	GameFloor: class extends self.ITiledBackgroundInstance {},
	LimitTrigger: class extends self.ISpriteInstance {},
	CompanyLogo: class extends self.ISpriteInstance {},
	MenuBackground: class extends self.ISpriteInstance {},
	MenuXrp: class extends self.ISpriteInstance {},
	NextUI: class extends self.ISpriteInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	InstructionsBTN: class extends self.ISpriteInstance {},
	MainScoreUI: class extends self.ISpriteInstance {},
	SettingsBTN: class extends self.ISpriteInstance {},
	MergeEffect: class extends self.ISpriteInstance {},
	GameOverScoreFont: class extends self.ISpriteFontInstance {},
	Instructions: class extends self.ISpriteInstance {},
	resized_shared0sheet: class extends self.ISpriteInstance {},
	Type2: class extends self.ISpriteInstance {},
	Type1: class extends self.ISpriteInstance {}
}